## docker-compose.yml

services:
  web:
    build: .
    env_file: .env
    ports:
      - "80:8000"  # host:container
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 15s
      timeout: 3s
      retries: 8